Repository depromeet/Whatnow-Api, pull requests merged in 2023-06, with the labels that each got.

#58 [DPMBE-57] Health Check API 생성
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/example/controller/ExampleController.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/config/security/SecurityConfig.kt
Labels: function

#59 [DPMBE-49] 약속 유저 매칭 데이터 생성, 수정, 삭제, 조회 기능을 만든다
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/promiseprogress/usecase/PromiseProgressReadUseCase.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/promiseuser/controller/PromiseUserController.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/promiseuser/dto/PromiseUserDto.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/promiseuser/usecase/PromiseUserReadUseCase.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/promiseuser/usecase/PromiseUserRecordUseCase.kt
  Whatnow-Api/src/test/kotlin/com/depromeet/whatnow/api/promiseuser/usecase/PromiseUserReadUseCaseTest.kt
  Whatnow-Api/src/test/kotlin/com/depromeet/whatnow/api/promiseuser/usecase/PromiseUserRecordUseCaseTest.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/promise/domain/Promise.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/promise/domain/PromiseRegisterEvent.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/promise/service/PromiseDomainService.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/promiseuser/adaptor/PromiseUserAdaptor.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/promiseuser/domain/PromiseUser.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/promiseuser/domain/PromiseUserType.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/promiseuser/exception/PromiseUserErrorCode.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/promiseuser/exception/PromiseUserNotFoundException.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/promiseuser/repository/PromiseUserRepository.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/promiseuser/service/PromiseDomainService.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/promiseuser/service/PromiseUserDomainService.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/events/domainEvent/EndTimePromiseEvent.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/events/domainEvent/MeetPromiseUserEvent.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/events/domainEvent/PromiseRegisterEvent.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/events/domainEvent/PromiseUpdateEvent.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/events/domainEvent/PromiseUserCancelEvent.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/events/domainEvent/PromiseUserRegisterEvent.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/events/handler/EndTimePromiseUserEventHandler.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/events/handler/PromiseUserRegisterHandler.kt
  build.gradle.kts
Labels: function

#68 [DPMBE-57] feat : 약속 단계 히스토리 init, 업데이트 , 조회 기능 추가
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/example/controller/ExampleController.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/promiseprogress/controller/PromiseProgressController.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/promiseprogress/dto/response/UserProgressResponse.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/promiseprogress/usecase/ProgressHistoryChangeUseCase.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/promiseprogress/usecase/ProgressHistoryReadUseCase.kt
  Whatnow-Common/src/main/kotlin/com/depromeet/whatnow/annotation/Handler.kt
  Whatnow-Common/src/main/kotlin/com/depromeet/whatnow/consts/WhatNowStatic.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/progresshistory/adapter/ProgressHistoryAdapter.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/progresshistory/domain/ProgressHistory.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/progresshistory/exception/PromiseHistoryErrorCode.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/progresshistory/exception/PromiseHistoryNotFoundException.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/progresshistory/exception/PromiseIsSameException.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/progresshistory/handler/PromiseUserRegisterHistoryCancelHandler.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/progresshistory/handler/PromiseUserRegisterHistoryInitHandler.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/progresshistory/repository/ProgressHistoryRepository.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/progresshistory/service/ProgressHistoryDomainService.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/promiseprogress/adapter/PromiseProgressAdapter.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/promiseuser/domain/PromiseUser.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/events/domainEvent/PromiseUserCancelEvent.kt
  build.gradle.kts
Labels: function

#76 [DPMBE-55] feat : 회원가입,로그인 및 fcm 토큰 업데이트 기능 추가
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/auth/controller/AuthController.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/auth/dto/request/LoginRequest.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/auth/dto/request/RegisterRequest.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/auth/usecase/LoginUseCase.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/auth/usecase/RefreshUseCase.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/auth/usecase/RegisterUserUseCase.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/user/controller/UserController.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/user/dto/request/UpdateFcmTokenRequest.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/user/usecase/ReadUserUseCase.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/user/usecase/UpdateUserUseCase.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/user/adapter/UserAdapter.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/user/domain/FcmNotificationVo.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/user/domain/User.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/user/service/UserDomainService.kt
  Whatnow-Domain/src/test/kotlin/com/depromeet/whatnow/domains/user/service/UserDomainServiceTest.kt
  Whatnow-Domain/src/test/kotlin/com/depromeet/whatnow/helper/UserFixture.kt
Labels: function

#73 [DPMBE-61] 이미지 성공 확인 시 late, wait에 따라 각각 다른 메세지를 보내도록 만든다.
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/example/controller/ExampleController.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/picture/controller/PictureController.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/picture/usecase/PictureUploadSuccessUseCase.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/picture/adapter/PromiseAdapter.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/picture/domain/Picture.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/picture/domain/PictureCommentType.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/picture/exception/CancelledUserUploadException.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/picture/exception/InvalidCommentTypeException.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/picture/exception/PictureErrorCode.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/picture/exception/UploadBeforeTrackingException.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/picture/service/PictureDomainService.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/events/handler/PictureRegisterEventHandler.kt
  Whatnow-Domain/src/test/kotlin/com/depromeet/whatnow/events/handler/PictureRegisterEventHandlerTest.kt
Labels: function

#77 [DPMBE-62] refactor : 약속 유저단계 enum 으로 관리 리팩토링
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/promiseprogress/controller/PromiseProgressController.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/promiseprogress/dto/response/PromiseProgressDto.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/promiseprogress/dto/response/PromiseProgressGroupElement.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/promiseprogress/dto/response/UserProgressResponse.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/promiseprogress/usecase/ProgressHistoryChangeUseCase.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/promiseprogress/usecase/ProgressHistoryReadUseCase.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/promiseprogress/usecase/PromiseProgressReadUseCase.kt
  Whatnow-Common/src/main/kotlin/com/depromeet/whatnow/consts/WhatNowStatic.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/progresshistory/domain/ProgressHistory.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/progresshistory/domain/PromiseProgress.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/progresshistory/domain/PromiseProgressGroup.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/progresshistory/exception/ProgressIsSameException.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/progresshistory/service/ProgressHistoryDomainService.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/promise/service/PromiseDomainService.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/promiseprogress/adapter/PromiseProgressAdapter.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/promiseprogress/domain/PromiseProgress.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/promiseprogress/exception/PromiseProgressCode.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/promiseprogress/exception/PromiseProgressNotFoundException.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/promiseprogress/repository/PromiseProgressRepository.kt
  Whatnow-Domain/src/main/resources/data.sql
Labels: enhancement

#72 [DPMBE-58] 약속 생성, 삭제, 수정 비즈니스 로직을 작성한다
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/promise/annotation/RequiresMainUser.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/promise/annotation/RequiresMainUserAspect.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/promise/controller/PromiseController.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/promise/dto/PromiseDto.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/promise/dto/PromiseFindDto.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/promise/dto/PromiseRequest.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/promise/usecase/PromiseReadUseCase.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/promise/usecase/PromiseRegisterUseCase.kt
  Whatnow-Api/src/test/kotlin/com/depromeet/whatnow/api/promiseuser/usecase/PromiseUserRecordUseCaseTest.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/common/vo/UserInfoVo.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/promise/adaptor/PromiseAdaptor.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/promise/domain/Promise.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/promise/domain/PromiseType.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/promise/exception/NotHostException.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/promise/exception/PromiseErrorCode.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/promise/service/PromiseDomainService.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/promiseuser/adaptor/PromiseUserAdaptor.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/promiseuser/repository/PromiseUserRepository.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/events/domainEvent/PromiseCancelEvent.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/events/domainEvent/PromiseRegisterEvent.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/events/domainEvent/PromiseUpdateEndTimeEvent.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/events/domainEvent/PromiseUpdateMeetPlaceEvent.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/events/handler/EndTimePromiseUserEventHandler.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/events/handler/PromiseRegisterEventHandler.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/events/handler/PromiseUserRegisterEventHandler.kt
Labels: function

#78 [DPMBE-63] 이미지 관련 테스트 코드를 작성한다
  Whatnow-Api/build.gradle.kts
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/image/controller/ImageController.kt
  Whatnow-Api/src/test/kotlin/com/depromeet/whatnow/api/image/controller/ImageControllerTest.kt
  Whatnow-Api/src/test/kotlin/com/depromeet/whatnow/api/image/usecase/GetPresignedUrlUseCaseTest.kt
  Whatnow-Api/src/test/kotlin/com/depromeet/whatnow/api/picture/controller/PictureControllerTest.kt
  Whatnow-Api/src/test/kotlin/com/depromeet/whatnow/api/picture/usecase/PictureUploadSuccessUseCaseTest.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/picture/adapter/PictureAdapter.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/picture/service/PictureDomainService.kt
  Whatnow-Domain/src/test/kotlin/com/depromeet/whatnow/domains/picture/adapter/PictureAdapterTest.kt
  Whatnow-Domain/src/test/kotlin/com/depromeet/whatnow/domains/picture/service/PictureDomainServiceTest.kt
  Whatnow-Infrastructure/src/test/kotlin/com/depromeet/whatnow/config/s3/S3PropertiesTest.kt
  Whatnow-Infrastructure/src/test/kotlin/com/depromeet/whatnow/config/s3/S3UploadPresignedUrlServiceTest.kt
Labels: test

#81 [DPMBE-64] FCM 기능을 추가한다
  Whatnow-Infrastructure/build.gradle.kts
  Whatnow-Infrastructure/src/main/kotlin/com/depromeet/whatnow/config/fcm/FcmConfig.kt
  Whatnow-Infrastructure/src/main/kotlin/com/depromeet/whatnow/config/fcm/FcmService.kt
  Whatnow-Infrastructure/src/main/resources/application-infrastructure.yml
Labels: enhancement

#82 [DPMBE-65] 스웨거 도커 태그 기반 버져닝 표시를 해준다
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/config/swagger/SwaggerConfig.kt
  Whatnow-Api/src/main/resources/application.yml
Labels: enhancement

#88 feat : PromiseRegisterEventHandler 구현
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/promise/domain/Promise.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/events/domainEvent/PromiseRegisterEvent.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/events/handler/PromiseRegisterEventHandler.kt
Labels: function, enhancement

#110 [DPMBE-80] 약속 모음집 상세 조회할 수 있다.(D3_상세 조회)
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/promise/controller/PromiseController.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/promise/dto/LocationCapture.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/promise/dto/PromiseDetailDto.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/promise/dto/PromiseUserInfoVo.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/promise/usecase/PromiseReadUseCase.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/promiseuser/dto/PromiseUserDto.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/user/usecase/ReadUserUseCase.kt
  Whatnow-Api/src/test/kotlin/com/depromeet/whatnow/api/promise/usecase/PromiseReadUseCaseTest.kt
  Whatnow-Api/src/test/kotlin/com/depromeet/whatnow/api/promiseuser/usecase/PromiseUserReadUseCaseTest.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/user/adapter/UserAdapter.kt
Labels: enhancement
