Repository depromeet/Whatnow-Api, pull requests merged in 2023-07, with the labels that each got.

#140 [DPMBE-92] Redis Expire Event MessageListener로 약속, 트래킹 이벤트 생성
  Whatnow-Common/src/main/kotlin/com/depromeet/whatnow/consts/WhatNowStatic.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/config/RedisMessageListenerConfig.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/promiseactive/adapter/PromiseActiveAdapter.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/promiseactive/domain/PromiseActiveRedisEntity.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/promiseactive/listener/RedisExpireEventRedisMessageListener.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/promiseactive/repository/PromiseActiveRepository.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/events/domainEvent/PromiseTimeEndEvent.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/events/domainEvent/PromiseTimeStartEvent.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/events/domainEvent/PromiseTrackingTimeEndEvent.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/events/handler/PromiseActivationEventHandler.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/events/handler/PromiseTimeEndEventHandler.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/events/handler/PromiseTimeStartEventHandler.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/events/handler/PromiseTrackingTimeEndEventHandler.kt
  Whatnow-Infrastructure/src/main/resources/application-infrastructure.yml
Labels: enhancement

#143 [DPMBE-98] ImageComment Enum에 이미지 링크를 추가하고 확인할 수 있도록 한다.
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/image/controller/ImageController.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/image/dto/ImageCommentElement.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/image/usecase/ImageCommentReadUseCase.kt
  Whatnow-Api/src/test/kotlin/com/depromeet/whatnow/api/image/controller/PromiseImageControllerTest.kt
  Whatnow-Common/src/main/kotlin/com/depromeet/whatnow/consts/WhatNowStatic.kt
  Whatnow-Domain/src/main/kotlin/com/depromeet/whatnow/domains/image/domain/PromiseImageCommentType.kt
Labels: function

#162 [DPMBE-104] 약속 조회 기능에 주소를 추가및 정렬 기준 추가한다
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/promise/controller/PromiseController.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/promise/dto/PromiseDetailDto.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/promise/dto/PromiseFindDto.kt
  Whatnow-Api/src/main/kotlin/com/depromeet/whatnow/api/promise/usecase/PromiseReadUseCase.kt
  Whatnow-Api/src/test/kotlin/com/depromeet/whatnow/api/promise/usecase/PromiseReadUseCaseTest.kt
Labels: enhancement

#172 [DPMBE-105] Slack 미발송 에러 해결
  Whatnow-Common/src/main/kotlin/com/depromeet/whatnow/consts/WhatNowStatic.kt
  Whatnow-Infrastructure/src/main/kotlin/com/depromeet/whatnow/api/config/slack/SlackAsyncErrorSender.kt
  Whatnow-Infrastructure/src/main/kotlin/com/depromeet/whatnow/api/config/slack/SlackErrorNotificationProvider.kt
  Whatnow-Infrastructure/src/main/kotlin/com/depromeet/whatnow/api/config/slack/SlackHelper.kt
  Whatnow-Infrastructure/src/main/kotlin/com/depromeet/whatnow/api/config/slack/SlackServiceNotificationProvider.kt
Labels: bug
